#!/bin/sh
#~/.shell_aliases
#This is my alias for archlinux
#
#Pacman package manager
# Pacman alias examples
#
#env
_isarch=false
[[ -f /etc/arch-release ]] && _isarch=true

_isroot=false
[[ $UID -eq 0 ]] && _isroot=true

if $_isarch; then
  if $_isroot; then
    alias pacman='sudo pacman'
  fi
  alias pacupg='sudo pacman -Syu'		# Synchronize with repositories and then upgrade packages that are out of date on the local system.
  alias pacin='sudo pacman -S --noconfirm' # Install specific package(s) from the repositories
  alias pacins='sudo pacman -U'		# Install specific package not from the repositories but from a file
  alias pacre='sudo pacman -R'		# Remove the specified package(s), retaining its configuration(s) and required dependencies
  alias pacrem='sudo pacman -Rns'		# Remove the specified package(s), its configuration(s) and unneeded dependencies
  alias pacrep='pacman -Si'		# Display information about a given package in the repositories
  alias pacreps='pacman -Ss'		# Search for package(s) in the repositories
  alias pacloc='pacman -Qi'		# Display information about a given package in the local database
  alias paclocs='pacman -Qs'		# Search for package(s) in the local database
  alias paclo="pacman -Qdt"		# List all packages which are orphaned
  alias pacc="sudo pacman -Scc"		# Clean cache - delete all not currently installed package files
  alias paclf="pacman -Ql"		# List all files installed by a given package
  alias pacexpl="pacman -D --asexp"	# Mark one or more installed packages as explicitly installed
  alias pacimpl="pacman -D --asdep"	# Mark one or more installed packages as non explicitly installed
  alias pacmir='sudo pacman -Syy'                    # Force refresh of all package lists after updating /etc/pacman.d/mirrorlist
fi
# '[r]emove [o]rphans' - recursively remove ALL orphaned packages
alias pacro="pacman -Qtdq > /dev/null && sudo pacman -Rns \$(pacman -Qtdq | sed -e ':a;N;$!ba;s/\n/ /g')"

#Directory and system
alias la='ls -la'
alias ll='ls -alh'
alias s='sudo'
alias reboot='systemctl reboot'
alias shutdown='systemctl poweroff'

#set python 2.7.8 default
alias python="/usr/bin/python2.7"
alias py="$HOME/soft/py27/bin/python"
